---
name: CI - Deploy Staging

on:
  pull_request:
    branches:
      - master
jobs:
  deploy:
    name: Deploy Staging
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v1
      - name: Config Access to AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-southeast-1

      - name: Lint
        run: |
          make lint

      - name: Unit/Integration Tests & Coverage
        run: |
          make test-integration

      - name: Pull configs
        run: |
          make pull-config-staging

      - name: Build Zip file
        run: |
          make build

      - name: Push Zip file to s3
        run: |
          make push      

      - name: Create Benstalk Application Version
        run: |
          make create-application-version

      - name: Deploy
        run: |
          make deploy
